ui: mocha-bdd
globals: token
concurrency: 1
browsers:
  - name: chrome
    version: [26, latest]
  - name: safari
    version: [5, latest]
  - name: firefox
    version: [4, latest]
  - name: ie
    version: [9, latest]
  - name: microsoftedge
    version: [13, latest]
  - name: opera
    version: [11, latest]
  - name: android
    version: [4.4, latest]
  - name: iphone
    version: [8.1, latest]
  - name: ipad
    version: [8.1, latest]
